### PR TITLE
Blueprint modding

### PR DESCRIPTION
**Pull request by nieboczek**
check out #1, with so many commits it becomes more and more apart from each other, which will become merging hell

### CODE REVIEW

**Comment by Boxofbiscuits97** [comment]
What should I do to prevent merging from being such a pain?

**Comment by nieboczek** [comment]
you should be up to date with this branch, you could rebase your changes in your fork onto the current commit

**Comment by nieboczek** [comment]
yeah that works

**Comment by nieboczek** [comment]
now you can continue doing your progress on blueprint mods

**Pull request closed without merging**
